apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  name: database-user2
  namespace: examplegitops
  labels:
    migration: d1ea1443-a5df-448d-82de-ca5a840b23dc
    plan: 6c46f7c7-6082-4b3e-bf67-ad897afd50e5
    vmID: vm-109089
spec:
  preference:
    kind: virtualmachineclusterpreference
    name: centos.stream9
  runStrategy: RerunOnFailure
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: database-user2
    spec:
      architecture: amd64
      domain:
        clock:
          timezone: UTC
        cpu:
          cores: 1
          sockets: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: vol-0
          inputs:
            - bus: virtio
              name: tablet
              type: tablet
          interfaces:
            - macAddress: '00:50:56:af:ea:37'
              masquerade: {}
              model: virtio
              name: net-0
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
          serial: 422f34de-72ed-c35b-5038-b7b10bdf171b
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: net-0
          pod: {}
      volumes:
        - name: vol-0
          persistentVolumeClaim:
            claimName: copy-of-database-vm-109089-8l7gs