apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubemacpool.io/transaction-timestamp: "2025-04-17T20:34:12.219065352Z"
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  labels:
    migration: a7ec8619-f8aa-4a36-ac22-3529573463d4
    plan: 2127b6e6-ab68-4f04-8b0a-56205b097273
    vmID: vm-109089
  name: database-user2
  namespace: examplegitops
spec:
  preference:
    kind: virtualmachineclusterpreference
    name: centos.stream9
    revisionName: database-user2-centos.stream9-v1beta1-b7030d00-b940-4ce1-a49b-2c9fb53a5d44-1
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: database-user2
    spec:
      architecture: amd64
      domain:
        clock:
          timezone: UTC
        cpu:
          cores: 1
          sockets: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: vol-0
          inputs:
          - bus: virtio
            name: tablet
            type: tablet
          interfaces:
          - macAddress: 00:50:56:af:ea:37
            model: virtio
            name: net-0
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
          serial: 422f34de-72ed-c35b-5038-b7b10bdf171b
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
      networks:
      - name: net-0
      volumes:
      - name: vol-0
        persistentVolumeClaim:
          claimName: vmspher3-vm-109089-wphd4