apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubemacpool.io/transaction-timestamp: "2025-04-17T20:39:51.839489089Z"
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  labels:
    migration: a7ec8619-f8aa-4a36-ac22-3529573463d4
    plan: 2127b6e6-ab68-4f04-8b0a-56205b097273
    vmID: vm-109109
  name: winweb01-user2
  namespace: examplegitops
spec:
  preference:
    kind: virtualmachineclusterpreference
    name: windows.2k22
    revisionName: winweb01-user2-windows.2k22-v1beta1-f27f9f4e-8a5c-4f79-a5a3-9ce658447de5-1
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: winweb01-user2
    spec:
      architecture: amd64
      domain:
        clock:
          timezone: UTC
        cpu:
          cores: 2
          sockets: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: vol-0
          inputs:
          - bus: virtio
            name: tablet
            type: tablet
          interfaces:
          - macAddress: 00:50:56:af:af:7a
            model: virtio
            name: net-0
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
          serial: 422fa560-b1a8-5006-4d43-6ed39d3758d4
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 6Gi
      networks:
      - name: net-0
        pod: {}
      volumes:
      - name: vol-0
        persistentVolumeClaim:
          claimName: vmspher3-vm-109109-chxz6