apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2k22-apricot-basilisk-61
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:vm.kubevirt.io/validations': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:vm.kubevirt.io/template': {}
            'f:vm.kubevirt.io/template.namespace': {}
            'f:vm.kubevirt.io/template.revision': {}
            'f:vm.kubevirt.io/template.version': {}
        'f:spec':
          .: {}
          'f:dataVolumeTemplates': {}
          'f:running': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:annotations':
                .: {}
                'f:vm.kubevirt.io/flavor': {}
                'f:vm.kubevirt.io/os': {}
                'f:vm.kubevirt.io/workload': {}
              'f:labels':
                .: {}
                'f:kubevirt.io/domain': {}
                'f:kubevirt.io/size': {}
                'f:network.kubevirt.io/headlessService': {}
            'f:spec':
              .: {}
              'f:architecture': {}
              'f:domain':
                .: {}
                'f:clock':
                  .: {}
                  'f:timer':
                    .: {}
                    'f:hpet':
                      .: {}
                      'f:present': {}
                    'f:hyperv': {}
                    'f:pit':
                      .: {}
                      'f:tickPolicy': {}
                    'f:rtc':
                      .: {}
                      'f:tickPolicy': {}
                  'f:utc': {}
                'f:cpu':
                  .: {}
                  'f:cores': {}
                  'f:sockets': {}
                  'f:threads': {}
                'f:devices':
                  .: {}
                  'f:disks': {}
                  'f:inputs': {}
                  'f:interfaces': {}
                  'f:tpm':
                    .: {}
                    'f:persistent': {}
                'f:features':
                  .: {}
                  'f:acpi': {}
                  'f:apic': {}
                  'f:hyperv':
                    'f:runtime': {}
                    'f:vpindex': {}
                    'f:frequencies': {}
                    'f:vapic': {}
                    'f:reenlightenment': {}
                    .: {}
                    'f:tlbflush': {}
                    'f:synic': {}
                    'f:ipi': {}
                    'f:spinlocks':
                      .: {}
                      'f:spinlocks': {}
                    'f:synictimer':
                      .: {}
                      'f:direct': {}
                    'f:relaxed': {}
                    'f:reset': {}
                  'f:smm': {}
                'f:firmware':
                  .: {}
                  'f:bootloader':
                    .: {}
                    'f:efi':
                      .: {}
                      'f:persistent': {}
                      'f:secureBoot': {}
                'f:memory':
                  .: {}
                  'f:guest': {}
              'f:networks': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes': {}
      manager: Mozilla
      operation: Update
      time: '2025-04-11T22:14:52Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:kubevirt.io/latest-observed-api-version': {}
            'f:kubevirt.io/storage-observed-api-version': {}
          'f:finalizers':
            .: {}
            'v:"kubevirt.io/virtualMachineControllerFinalize"': {}
      manager: virt-controller
      operation: Update
      time: '2025-04-11T22:14:52Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:printableStatus': {}
          'f:runStrategy': {}
          'f:conditions': {}
          .: {}
          'f:ready': {}
          'f:volumeSnapshotStatuses': {}
          'f:observedGeneration': {}
          'f:created': {}
          'f:desiredGeneration': {}
      manager: virt-controller
      operation: Update
      subresource: status
      time: '2025-04-14T11:44:39Z'
  namespace: exampleproject
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: win2k22-apricot-basilisk-61
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 60Gi
    - metadata:
        creationTimestamp: null
        name: win2k22-apricot-basilisk-61-installation-cdrom
      spec:
        source:
          pvc:
            name: windows22
            namespace: exampleproject
        storage:
          resources:
            requests:
              storage: '10737418240'
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: windows2k22
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: win2k22-apricot-basilisk-61
        kubevirt.io/size: medium
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 2
              disk:
                bus: sata
              name: rootdisk
            - bootOrder: 3
              cdrom:
                bus: sata
              name: windows-drivers-disk
            - bootOrder: 1
              cdrom:
                bus: sata
              name: installation-cdrom
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - macAddress: '02:76:c3:00:00:1a'
              masquerade: {}
              model: e1000e
              name: default
          tpm:
            persistent: true
        features:
          acpi: {}
          apic: {}
          hyperv:
            reenlightenment: {}
            ipi: {}
            synic: {}
            synictimer:
              direct: {}
            spinlocks:
              spinlocks: 8191
            reset: {}
            relaxed: {}
            vpindex: {}
            runtime: {}
            tlbflush: {}
            frequencies: {}
            vapic: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              persistent: true
              secureBoot: true
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 3600
      volumes:
        - dataVolume:
            name: win2k22-apricot-basilisk-61
          name: rootdisk
        - containerDisk:
            image: 'registry.redhat.io/container-native-virtualization/virtio-win-rhel9@sha256:2e50092a246c4e39d449201ff12a8fd9c3cbeebcf100a653990f0dce6972846d'
          name: windows-drivers-disk
        - dataVolume:
            name: win2k22-apricot-basilisk-61-installation-cdrom
          name: installation-cdrom