project: default
source:
  repoURL: 'https://github.com/ravishar-rh/gitopsexample.git'
  path: exampleproject/vms/windows
  targetRevision: HEAD
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: 'https://kubernetes.default.svc'
  namespace: exampleproject
syncPolicy:
  automated:
    prune: true
    selfHeal: true
