apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: winweb02-user2
  namespace: examplegitops
spec:
  runStrategy: RerunOnFailure
    spec:
      domain:
        clock:
          timezone: PDT
        memory:
          guest: 8Gi