apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: VirtualMachine
      name: winweb02-user2
    patch: |-
      - op: replace
        path: /spec/domain/memomry/guest
        value: 8Gi