apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: virtualmachineclusterpreference
      name: windows.2k22
    patch: |-
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 8Gi